<div id="inside-post-wrapper">
        
        
                <div class="block-header type-1">
        <h1 class="the-h3">
        Privacy Policy    </h1>
    <p class="block-description"></p></div>        
        <div class="table-layout">
                        <div class="table-cell valign-top">
                            </div>
        </div>

        <div>
        </div>

        
                                <div class="wp-content clear main-read the-640" style="">
            <p><strong>BACALAH KEBIJAKAN PRIVASI INI DENGAN HATI-HATI, CERMAT DAN TELITI AGAR ANDA DAPAT MENGERTI DAN MEMAHAMI KEBIJAKAN YANG KAMI TERAPKAN DALAM MENGATUR INFORMASI PRIBADI ANDA SEBELUM ANDA MENGGUNAKAN LAYANAN DARI SITUS WEB <a href="https://www.ellafroze.com">www.ellafroze.com</a></strong></p>
<p>Kebijakan Privasi ini berisi penjelasan atas perlindungan dan penggunaan data dan/atau informasi pribadi pengguna (“Pengguna“) dalam situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp;yang dikelola oleh ELLA FROZE (“Ella Froze“).</p>
<p>Kebijakan Privasi ini berlaku untuk setiap informasi yang dikumpulkan dan digunakan oleh Ella Froze ketika anda sebagai pengguna (“Pengguna“) mengakses dan/atau menggunakan situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp;serta layanan online ataupun seluler lainnya yang menautkan kebijakan Privasi ini kepada Pengguna.</p>
<p>&nbsp;</p>
<h2>Data Pribadi Pengguna</h2>
<p>Untuk dapat mengakses layanan pada situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>, Pengguna perlu melakukan registrasi dan melengkapi informasi berupa nama, alamat email, nomor telepon, serta informasi lain yang dibutuhkan Ella Froze. Ella Froze juga dapat meminta data tambahan yang bersifat opsional tetapi harus diisi untuk memungkinkan Ella Froze memberikan layanan tambahan kepada Pengguna.</p>
<p>Pengguna menjamin dan menyatakan bahwa setiap Informasi yang diberikan oleh Pengguna kepada Ella Froze dalam situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp;adalah informasi yang akurat, valid dan sah. Ella Froze mewajibkan Pengguna untuk mengirimkan informasi dasar untuk memudahkan proses verifikasi identitas pengguna, dan memastikan pengguna sudah berusia dewasa secara hukum. Jika informasi, termasuk perubahan informasi yang diberikan Pengguna tersebut ternyata tidak benar maka Ella Froze tidak bertanggung jawab atas segala dan setiap akibat yang dapat terjadi sehubungan dengan pemberian informasi yang tidak benar tersebut.</p>
<p>&nbsp;</p>
<h2>Batasan Usia</h2>
<p>Ella Froze mematuhi batasan dan persyaratan usia sesuai dengan hukum yang berlaku. Layanan dalam situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a> ini diperuntukkan bagi Pengguna yang&nbsp;berusia minimal 18 tahun atau sudah menikah dan tidak berada di bawah perwalian. Jika Ella Froze mengetahui bahwa Ella Froze secara tidak sengaja telah mengumpulkan informasi pribadi dari Pengguna yang berusia dibawah 18 tahun tanpa persetujuan orang tua dan/atau wali yang sah, maka Ella Froze akan meminta Pengguna untuk meminta persetujuan dari orang tua dan/atau wali yang sah untuk mendaftar dalam&nbsp;situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>. Jika Ella Froze tidak mendapatkan informasi persetujuan&nbsp;orang tua dan/atau wali yang sah&nbsp;dalam akun pendaftaran Pengguna maka Ella Froze akan mengambil langkah yang wajar untuk menghapus informasi pribadi Pengguna sesegera mungkin.</p>
<p>&nbsp;</p>
<h2>Pengumpulan dan Penggunaan Data Pribadi</h2>
<p>Semua informasi pribadi Pengguna yang diberikan secara sukarela pada saat registrasi akan disimpan dan dan dilindungi oleh Ella Froze sesuai dengan ketentuan dalam Kebijakan Privasi ini. Informasi pribadi Pengguna akan digunakan untuk keperluan Ella Froze, termasuk namun tidak terbatas &nbsp;dalam proses&nbsp;<i>login</i>&nbsp;maupun&nbsp;<i>log out</i> pada situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>, untuk kepentingan survey serta riset dalam rangka meningkatkan meningkatkan kinerja dan keamanan situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp;serta layanan online.</p>
<p>Ella Froze mengumpulkan informasi pribadi Pengguna sewaktu Pengguna menggunakan situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>, termasuk namun tidak terbatas pada informasi lokasi umum yang meliputi informasi geografis, alamat IP, kota dan negara bagian dan/atau kode pos yang terkait dengan alamat IP dari perangkat seluler serta komputer Pengguna; sumber rujukan; lama waktu Pengguna menggunakan layanan dari situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>; periode kunjungan;&nbsp;<i>page views</i> dan klik, maupun &nbsp;informasi lainnya didapatkan Ella Froze secara otomatis sewaktu Pengguna mendaftar dan/atau mengunggah data dan/atau menggunakan layanan pada situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>. Ella Froze juga mengumpulkan data dari akun media sosial yang diijinkan oleh Pengguna untuk diakses oleh Ella Froze.</p>
<p>Ella Froze juga akan mengirimkan update berkala pada akun Pengguna selama periode tertentu &nbsp;dalam bentuk informasi dan/atau promosi dan/atau perubahan pada situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp;yang akan berpengaruh terhadap Pengguna.</p>
<p>Pengguna setuju dan mengijinkan Ella Froze memberikan dan/atau mendistribusikan data pribadi Pengguna kepada pihak ketiga yang telah melakukan kerjasama dengan Ella Froze untuk tujuan administrasi dan/atau penawaran produk dan/atau dalam rangka meningkatan layanan terhadap Pengguna.</p>
<p>&nbsp;</p>
<h2>Hak Pengguna</h2>
<p>Sesuai dengan ketentuan hukum yang berlaku di Indonesia, Pengguna berhak mengajukan permintaan kepada Ella Froze, untuk (a) memberikan akses ke dan/atau salinan informasi pribadi Pengguna yang disimpan dalam situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>; (b) perubahan dan/atau penambahan dan/atau pembaruan data pribadi Pengguna; (c) menghapus informasi pribadi Pengguna dari situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>; (d) mencegah penggunaan dan/atau pemrosesan informasi pribadi Pengguna untuk tujuan pemasaran dan/atau memberikan informasi tentang Pengguna kepada penyedia layanan pihak ketiga.</p>
<p>Pengguna dapat mengirimkan permintaan kepada Ella Froze dengan menghubungi layanan kontak Ella Froze yang tercantum dalam Kebijakan Privasi ini.</p>
<p>Ella Froze akan mempertimbangkan permintaan Pengguna dan memberikan tanggapan dalam jangka waktu yang ditentukan berdasarkan oleh hukum yang berlaku. Namun demikian, Pengguna mengerti dan memahami bahwa untuk informasi tertentu dan/atau situasi tertentu dan/atau keadaan tertentu, Ella Froze dapat mengecualikan permintaan Pengguna, termasuk jika Ella Froze memutuskan tetap memproses informasi pribadi Pengguna untuk kepentingan sah Ella Froze dan/atau untuk mematuhi kewajiban hukum. Ella Froze dapat meminta kepada Pengguna untuk memberikan informasi yang diperlukan untuk mengonfirmasi identitas Pengguna sebelum menanggapi permintaan Pengguna.</p>
<p>&nbsp;</p>
<h2>Keamanan Informasi dan Data Pengguna</h2>
<p>Ella Froze berkomitmen dan berintegritas dalam&nbsp;menjaga data dan informasi pribadi Pengguna, dimana data dan&nbsp;informasi pribadi Pengguna hanya akan digunakan terbatas untuk tujuan kegiatan Ella Froze dan tanpa tujuan lainnya.&nbsp;Ella Froze akan mengambil langkah keamanan teknis dan organisasi dalam melindungi Informasi yang diberikan Pengguna dalam website Ella Froze dari&nbsp;kehilangan, penyalahgunaan, dan akses tidak sah, pengungkapan, perubahan, atau penghancuran. Namun, tidak ada transmisi Internet atau email yang sepenuhnya aman atau bebas dari kesalahan, karena itu Pengguna disarankan memperhatikan hal ini saat mengungkapkan informasi apa pun&nbsp;kepada website Ella Froze&nbsp;melalui Internet.</p>
<p>Ella Froze membatasi staf yang memiliki akses ke data pengguna, dan sebagian besar dari mereka hanya memiliki akses ke bagian tertentu dari data yang diperlukan untuk melakukan tugas-tugas mereka sebagai bagian dari layanan kami. Staf Kami tidak diperbolehkan untuk mentransfer atau membawa keluar data dari server. &nbsp;Dalam hal diperlukan, Ella Froze akan mengirimkan notifikasi dari waktu ke waktu, untuk memastikan bahwa tidak ada pihak dan/atau orang lain yang membuat perubahan atas akun Pengguna tanpa sepengetahuan Pengguna.</p>
<p>&nbsp;</p>
<h2>Koneksi ke Situs Lain</h2>
<p>Untuk memudahkan Pengguna, situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp;menyediakan link ke situs-situs pihak ketiga lainnya. &nbsp;Masing-masing situs memiliki kebijakan penanganan privasi tersendiri, karena itu Pengguna harus berhati-hati dan mempelajari pernyataan Kebijakan privasi yang berlaku pada situs lain tersebut sebelum memberikan informasi pribadi. Ella Froze tidak bertanggung jawab atas isi dari situs lain tersebut dan/atau informasi apapun yang diberikan Pengguna kepada situs-situs tersebut.</p>
<p>&nbsp;</p>
<h2>Cookies</h2>
<p>Penerimaan cookie tidak merupakan persyaratan untuk mengunjungi situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>, namun kami ingin menunjukkan bahwa untuk pengumpulan informasi yang diperoleh Ella Froze secara otomatis dari situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>, Ella Froze menggunakan log server internet, cookie dan teknologi pelacakan serupa lainnya. Teknologi ini digunakan agar Ella Froze dapat memahami dan mengingat preferensi penjelajahan anda. Cookie adalah file teks kecil yang mengidentifikasi komputer Pengguna ke server Ella Froze yang memungkinkan Ella Froze mengenali anda sebagai pengguna unik ketika Pengguna mengunjungi halaman tertentu dari situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>, dan disimpan oleh browser Internet pada hard drive komputer Pengguna. Cookies dapat digunakan untuk mengenali alamat Internet Protocol Pengguna, menghemat waktu saat berada di, atau ingin memasuki situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>.</p>
<p>Ella Froze hanya mempergunakan cookies untuk kenyamanan Pengguna dalam menggunakan situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>. Browser Pengguna dapat diatur untuk tidak menerima cookie, tapi ini akan membatasi penggunaan layanan dari situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>.</p>
<p>&nbsp;</p>
<h2>Perubahan Kebijakan Privasi</h2>
<p>Ella Froze berhak mengubah, menambah ataupun mengurangi Kebijakan Privasi ini dari waktu ke waktu sebagai bagian dari upaya Ella Froze untuk melayani pengguna dengan lebih baik. Oleh karena itu Pengguna dianjurkan untuk mempelajari Kebijakan Privasi ini secara berkala agar mengetahui perubahan-perubahan terbaru dari Ella Froze.</p>
<p>Pengguna dapat mengetahui adanya perubahan atas kebijakan Privasi dengan melihat pada tanggal revisi yang dicantumkan di bagian bawah dari Kebijakan Privasi ini.</p>
<p>Apabila Ella Froze melakukan perubahan yang bersifat material maka Ella Froze akan memberikan pemberitahuan yang sesuai dengan tatacara yang ditetapkan oleh peraturan hukum yang berlaku.</p>
<p>Dengan terus menggunakan layanan dalam situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp;ini Pengguna mengkonfirmasi bahwa Pengguna telah membaca, mengerti dan memahami versi terbaru dari Kebijakan Privasi ini.</p>
<p>&nbsp;</p>
<h2>Informasi Kontak</h2>
<p>Jika Pengguna memiliki pertanyaan tentang Kebijakan Privasi <a href="https://www.ellafroze.com">www.ellafroze.com</a> atau penggunaan informasi dari layanan situs web <a href="https://www.ellafroze.com">www.ellafroze.com</a> maka Pengguna dapat menghubungi kami melalui : <a href="https://www.ellafroze.com">www.ellafroze.com</a></p>
<p>&nbsp;</p>
<hr>
<p>&nbsp;</p>
<p><strong>BEFORE YOU USE THE SERVICE IN THE WEBSITE </strong><a href="https://www.ellafroze.com"><strong>www.ellafroze.com</strong></a><strong>, PLEASE READ THIS PRIVACY POLICY CAREFULLY AND THOROUGHLY IN ORDER TO UNDERSTAND THE POLICY WHICH WE APPLY IN MANAGING YOUR PERSONAL INFORMATION.</strong><strong>&nbsp;</strong></p>
<p>This following privacy policy contains the explanation about the protection and usage of users’ personal data and/or information (“User”) in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a> maintained by ELLA FROZE (“Ella Froze”).</p>
<p>This privacy policy is applied to all information collected and used by Ella Froze when you as users (“User”) access and/or use the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>&nbsp; including other online or mobile services that connect this privacy policy to the User.</p>
<p>&nbsp;</p>
<h2>USERS’ PERSONAL DATA</h2>
<p>To access the services provided in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>, Users need to register and complete information such as name, e-mail address, telephone number, and any other information needed by Ella Froze. Ella Froze may also ask additional information that is optional but required to allow Ella Froze to provide users with additional services.</p>
<p>Users guarantee and state that every information given by Users to Ella Froze in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a> is accurate and valid. Ella Froze requires Users to send basic information to facilitate the verification process of users’ identity and ensure users are legal adults. If the information, including information change, provided by the users is false, Ella Froze will not be responsible for every consequence that might happen due to the false information given.</p>
<p>&nbsp;</p>
<h2>AGE RESTRICTIONS</h2>
<p>Ella Froze obeys age restrictions and requirements based on the applicable law. Services in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a> are directed towards users of minimum 18 years of age or married and who are not under guardianship. If Ella Froze finds out that Ella Froze accidentally has collected personal information from Users below 18 years of age without consent from parents and/or legal guardians, Ella Froze will ask users to provide consent from parents and/or legal guardians to register in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>. If Ella Froze does not acquire consent from parents and/or legal guardians in Users’ register account, Ella Froze will take any necessary step to delete Users’ personal information as soon as possible.</p>
<p>&nbsp;</p>
<h2>PERSONAL DATA COLLECTION AND USAGE</h2>
<p>All of Users’ personal information given voluntarily during registration will be stored and protected by Ella Froze following the rules in this Privacy Policy. Users’ personal information will be used for Ella Froze’ necessity, including but not limited to either log-in or log-out process in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>, for survey and research purpose in order to improve the performance and security of <a href="https://www.ellafroze.com">www.ellafroze.com</a> and online services.</p>
<p>Ella Froze collects Users’ personal information when Users access <a href="https://www.ellafroze.com">www.ellafroze.com</a>, including but not limited to general location information that covers geographical information, IP address, city and state and/or postal code related to the IP address of the user’ mobile gadget and personal computer; refences; users’ time duration when accessing <a href="https://www.ellafroze.com">www.ellafroze.com</a>; visit period; page views and clicks, or any other information collected by Ella Froze automatically when Users register and/or upload data and/or use services in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>. Ella Froze also collects data from social media accounts permitted by the users to be accessed by Ella Froze.</p>
<p>Ella Froze will also send regular updates to Users’ accounts during a certain period in a form of information and/or promotion and/or changes in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a> which will affect the Users.</p>
<p>Users agree and permit Ella Froze to give and/or distribute Users’ personal data to third parties which have cooperated with Ella Froze for administration purposes and/or product offers and/or Users’ service improvement.</p>
<p>&nbsp;</p>
<h2>Users’ Rights</h2>
<p>In accordance with the law in Indonesia, Users have the right to request Ella Froze to (a) give access to and/or the copy of Users’ personal information stored in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>; (b) give access to changes and/or addition and/or revision of Users’ personal information; (c) delete Users’ personal information from the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>; (d) prevent usage and/or process of Users’ personal information for marketing purposes and/or give information about users to third party platforms.</p>
<p>Users can send request to Ella Froze by contacting Ella Froze customer service listed in this Privacy Policy.</p>
<p>Ella Froze will consider Users’ request and respond in time period determined by the applicable law. However, Users understand that for certain information and/or situations and/or condition, Ella Froze is able to exclude Users’ request for Ella Froze’ purpose and/or to obey the law. Ella Froze could ask Users to give information needed to confirm Users’ identity before responding to the Users’ requests.</p>
<p>&nbsp;</p>
<h2>Security of Users’ Information and Data</h2>
<p>Ella Froze is commited to and has the integrity to protect users’ personal data and information. Users’ personal and data information will only be used for Ella Froze’ activities without any other purpose. Ella Froze will take technical security and organization steps in protecting the information given by Users in Ella Froze website against loss, misuse, and illegal access, disclosure, changes, or destruction. However, no internet transmition nor e-mail that is completely safe or free from mistakes. Thus, Users are advised to pay attention to this issue when disclosing any information to Ella Froze’ website via internet.</p>
<p>Ella Froze limits the staff who have access to users’ data, and most of them only have access to certain part of the data needed to do their task as a part of our service. Our staff are not allowed to transfer or bring the data out from the server. If needed, Ella Froze will send notification from time to time, to make sure no one will make any change to Users’ account without agreemeent from Users.</p>
<p>&nbsp;</p>
<h2>Connection to Other Website</h2>
<p>For Users’ convenience, <a href="https://www.ellafroze.com">www.ellafroze.com</a> provides links to other third party websites. Each website has its own privacy policy; therefore, Users need to be aware and study the privacy policy applied in the other websites before giving personal information. Ella Froze is not responsible for the content of other websites and/or any information given by Users to those websites.</p>
<p>&nbsp;</p>
<h2>Cookies</h2>
<p>Accepting cookies is not a requirement to visit <a href="https://www.ellafroze.com">www.ellafroze.com</a>, yet we would like to show that for information automatically collected by Ella Froze from <a href="https://www.ellafroze.com">www.ellafroze.com</a>, Ella Froze uses log server internet, cookie, and similar tracking technology. This technology is used so Ella Froze can understand and remember your browing preference. Cookie is a small text file that identifies Users’ computer to Ella Froze server which allows Ella Froze to identify you as a unique user when Users visit a certain page in <a href="https://www.ellafroze.com">www.ellafroze.com</a>, and this is saved by the internet browser in Users’ computer hard drive. Cookies can be used to identify Users’ IP address, to save the time when you are visiting and or about to visit <a href="https://www.ellafroze.com">www.ellafroze.com</a>.</p>
<p>Ella Froze will only use cookies for Users’ convenience when accessing <a href="https://www.ellafroze.com">www.ellafroze.com</a>. Users’ browser can be set to not accept cookie, but this will limit the service usage from <a href="https://www.ellafroze.com">www.ellafroze.com</a>.</p>
<p>&nbsp;</p>
<h2>Changes to Privacy Policy</h2>
<p>Ella Froze has the right to change, add, or reduce this Privacy Policy from time to time as a part of Ella Froze’ efforts to give better service to Users. Thus, Users are advised to study this Privacy Policy regularly in order to know latest changes from Ella Froze.</p>
<p>Users can find out about the changes to this Privacy Policy by looking at the revision date listed under this Privacy Policy.</p>
<p>If Ella Froze makes any material change, Ella Froze will notify the Users following the guidelines assigned by the law.</p>
<p>By constantly using services in the website <a href="https://www.ellafroze.com">www.ellafroze.com</a>, Users have confirmed that Users have read and understood the latest version of this Privacy Policy.</p>
<p>&nbsp;</p>
<h2>Contact Information</h2>
<p>If Users have any questions regarding the privacy policy of <a href="https://www.ellafroze.com">www.ellafroze.com</a> or any information of service provided by <a href="https://www.ellafroze.com">www.ellafroze.com</a>, Users can contact us via: <a href="https://www.ellafroze.com">www.ellafroze.com</a></p>
        </div>